name: Node.js Tests

on:
  workflow_dispatch:
    branches-ignore: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.10.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.x'
          cache: 'npm'
          persist-credentials: false
      - name: Install dependencies
        run: npm ci
      - run: npm run tests:ci